// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://advgsnplgrnfoxvavxcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdmdzbnBsZ3JuZm94dmF2eGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzAwODYsImV4cCI6MjA2MTQ0NjA4Nn0.Pq7ie1YoPUeQf6ap4E6pRYZrxUfHf9yXhOjcm83AMXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);